#!/usr/bin/env bash

INSTALL_DEV=false
INSTALL_APPS=false

# Handle command line args
for arg in "$@"; do
  case $arg in
    --dev)
      INSTALL_DEV=true
      shift
      ;;
    --apps)
      INSTALL_APPS=true
      shift
      ;;
  esac
done

# Install any development tools and programming language tools
function install-dev() {
  # Install GitHub CLI
  if ! type gh &> /dev/null; then
    echo "Installing GitHub CLI"
    brew install --quiet gh
  fi

  brew install --quiet mise libpq docker shellcheck python pipx

  mise use -g go@latest
  mise use -g ruby@latest
  mise use -g node@latest
}

# Install any applications needed
function install-apps() {
  # Browsers
  brew install --quiet --cask google-chrome

  # Development
  brew install --quiet --cask visual-studio-code 
  brew install --quiet pre-commit

  # Fun
  brew install --quiet --cask spotify
}

function main() {
  # make sure config dir exists
  [[ -d "$HOME/.config" ]] || mkdir "$HOME/.config"

  # Install Homebrew
  if ! type "brew" &> /dev/null; then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  # Install jq
  if ! type "jq" &> /dev/null; then
    echo "Installing jq"
    brew install jq
  fi

  # Tools
  [[ -d "/Applications/iTerm.app" ]] || brew install --cask --quiet iterm2
  brew install --quiet zsh-autosuggestions zsh-syntax-highlighting starship neovim

  # Install z
  export Z_HOME="$HOME/zed"

  if [ ! -d "$Z_HOME" ]; then
    echo "Installing rupa/z"
    git clone https://github.com/rupa/z "$Z_HOME"
  else
    echo "Updating rupa/z"
    pushd "$Z_HOME" > /dev/null || exit
    git pull
    popd > /dev/null || exit
  fi

  # nvim config
  if [[ ! -L "$HOME/.config/nvim/init.lua" ]]; then
    ln -s "$(pwd)/assets/init.lua" "$HOME/.config/"
  fi

  # Optional installation...
  if [ "$INSTALL_DEV" == true ]; then
    install-dev
  fi

  if [ "$INSTALL_APPS" == true ]; then
    install-apps
  fi

  # Get the full path of .bash_config in the current folder
  BASH_CONFIG_PATH="$(pwd)/.bash_config"

  # Add .bash_config to ~/.zshrc if not already added
  if ! grep -Fxq "source $BASH_CONFIG_PATH" "$HOME/.zshrc"; then
    echo "source $BASH_CONFIG_PATH" >> "$HOME/.zshrc"
    echo "$(pwd)/.bash_config has been added to ~/.zshrc"
  fi
}

# Run the installer
main
