#!/usr/bin/env bash
NO_DEV=false
NO_APPS=false

# Handle command line args
for arg in "$@"; do
  case $arg in
    --no-dev)
      NO_DEV=true
      shift
      ;;
    --no-apps)
      NO_APPS=true
      shift
      ;;
  esac
done

# Install any development tools and programming language tools
function install-dev() {
  # Install GitHub CLI
  if ! type gh &> /dev/null; then
    echo "Installing GitHub CLI"
    brew install gh
  fi

  # NVM
  if [[ ! -d "$HOME/.nvm" ]]; then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  fi

  # Langs/frameworks
  brew install go rbenv libpq docker shellcheck
  rbenv init
}

# Install any applications needed
function install-apps() {
  # Browsers
  brew install --cask google-chrome

  # Development
  brew install --cask visual-studio-code iterm2

  # Fun
  brew install --cask spotify
}

function main() {
  # Copy the VIM profile
  if [[ ! -L "$HOME/.vimrc" ]]; then
    ln -s "$(pwd)/.vimrc" ~
  fi

  # Install Homebrew
  if ! type "brew" &> /dev/null; then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  # Install jq
  if ! type "jq" &> /dev/null; then
    echo "Installing jq"
    brew install jq
  fi

  # Install z
  export Z_HOME="$HOME/zed"

  if [ ! -d "$Z_HOME" ]; then
    echo "Installing rupa/z"
    git clone https://github.com/rupa/z "$Z_HOME"
  else
    echo "Updating rupa/z"
    pushd "$Z_HOME" > /dev/null || exit
    git pull
    popd > /dev/null || exit
  fi

  # Tools
  brew install zsh-autocomplete zsh-syntax-highlighting pre-commit neovim

  # Use .vimrc in neovim
  if [ ! -e "$HOME/.config/nvim/init.vim" ]; then
    cp "$(pwd)/support/init.vim" "$HOME/.config/nvim/init.vim" 
  fi

  if [ "$NO_DEV" == false ]; then
    install-dev
  fi

  if [ "$NO_APPS" == false ]; then
    install-apps
  fi

  # Get the full path of .bash_config in the current folder
  BASH_CONFIG_PATH="$(pwd)/.bash_config"
  echo "The full path of .bash_config is: $BASH_CONFIG_PATH"

  # Add .bash_config to ~/.zshrc if not already added
  if ! grep -Fxq "source $BASH_CONFIG_PATH" "$HOME/.zshrc"; then
    echo "source $BASH_CONFIG_PATH" >> "$HOME/.zshrc"
    echo ".bash_config has been added to ~/.zshrc"
  else
    echo ".bash_config is already sourced in ~/.zshrc"
  fi

  # Add ZSH plugins to ~/.zshrc
  if ! grep -Fq "zsh-autocomplete" "$HOME/.zshr"; then
    if [[ -d "$HOMEBREW_PREFIX/share/zsh-autocomplete" ]]; then
      echo "source $HOMEBREW_PREFIX/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh" >> "$HOME/.zshrc"
    fi
  fi
}

# Run the installer
main
